Feat: Add read/write_register function and struct
Maker-Tech-RnD/TMC5160-STM32-HAL pull request #2
Opened 2023-09-08 15:33 UTC by EmbededIlya

Add  function read/write_register  in main.c, stuct TMC5160_HandleTypeDef in main.h

2023-09-08 16:40 UTC, DuePonto requested changes
Оставил комментарии в местах, которые надо исправить, гляньте и подправьте

2023-09-08 16:40 UTC, DuePonto commented on TMC5160.c
> +	  HAL_GPIO_WritePin(htmc->GPIOx,htmc->CS, GPIO_PIN_RESET);
Для чего сделана эта пауза в начале? (34-38)
Думаю что не для чего, надо это дело почистить

2023-09-08 16:40 UTC, DuePonto commented on TMC5160.c
> +	  HAL_GPIO_WritePin(htmc->GPIOx,htmc->CS, GPIO_PIN_RESET);
Тут то-же самое, не нужно делать этого дрыганья

2023-09-08 16:40 UTC, DuePonto commented on TMC5160.c
> +	  reg_addr &= 0b01111111;
Для чего эта строчка?

2023-09-08 16:40 UTC, DuePonto commented on TMC5160.c
> +	  uint8_t buff[5];
Буфер надо заполнять до того как пин CS прижат к земле

2023-09-08 16:40 UTC, DuePonto commented on TMC5160.c
> +	  HAL_StatusTypeDef result = HAL_SPI_TransmitRecieve(htmc->_hspi, buff,data, 5, 100);
Если тут используем функцию TransmitRecieve, то почему не используем массив, который возвращается?

2023-09-08 16:40 UTC, DuePonto commented on TMC5160.c
> +	  HAL_Delay(1);
Пауза не нужна

2023-09-08 18:32 UTC, GreedlyCore commented on TMC5160.c
> +	  HAL_GPIO_WritePin(htmc->GPIOx,htmc->CS, GPIO_PIN_RESET);
я вроде удалял её, соглашусь

2023-09-08 18:36 UTC, DuePonto commented on TMC5160.c
> +	  HAL_GPIO_WritePin(htmc->GPIOx,htmc->CS, GPIO_PIN_RESET);
Илья заливал, может у него старая версия

2023-09-08 19:18 UTC, DuePonto commented
@GreedlyCore Ты говорил, что можно как то править код прям внутри гитхаба, как это можно сделать?
Или я что-то не так понял?

2023-09-08 20:35 UTC, GreedlyCore commented
@DuePonto не так ты понял, но и это можно сделать. В пул реквесте мы можем сказать, чтобы он доработал его новыми коммитами ( в ту же ветку просто льешь, ничего делать не надо больше, главное ветку не прикрыть), правки предложить цитированием вроде нельзя, ты можешь fetch сделать и сам дополнить пул реквест, залив что-то в ветку, от лица которой идёт пул реквест (1-add-readreg-writereg-functions). Главное тут не наткнуться, что Илья у себя локально одно успел сделать, ты другое (тоже локально), а потом оба хотите коммитить и обновлять пул реквест, тут скорее всего merge конфликты уже появятся, так что лучше понимать кто работает над этим пул реквестом и договариваться :)

2023-09-11 09:54 UTC, DuePonto requested changes

2023-09-11 09:54 UTC, DuePonto commented on TMC5160.c
>  	  HAL_GPIO_WritePin(htmc->GPIOx,htmc->CS, GPIO_PIN_RESET);
Это переключение в самом начале не нужно, нам же для передачи нужно CS в 0 опустить, а в конце передачи поднять в 1. Ничего перед этим делать не надо, лишние телодвижения - это лишнее время

2023-09-11 09:54 UTC, DuePonto commented on TMC5160.c
> +}
Тут стоп. Это нужно убрать, мы ещё не добили тут задачу, с тем чтобы добавить функции чтения и записи. А тут уже пошла настройка конфигурации - это нужно убрать

2023-09-11 09:57 UTC, DuePonto commented on TMC5160.c
> +	  uint8_t buff[5];
@EmbededIlya Это ещё не поправлено

2023-09-11 09:57 UTC, DuePonto commented on TMC5160.c
> +	  reg_addr &= 0b01111111;
@EmbededIlya Тут тоже ещё не поправлено

2023-09-12 09:39 UTC, DuePonto reviewed
Good. Very nice!

2023-09-12 09:39 UTC, DuePonto approved these changes
Good. Very nice!

2023-09-12 09:41 UTC, merged